# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: Gc9gHyzMRAvLtzCGVOuWIsVtx6bGqyWZ
            client-secret: RLK4NnEbHXEfLiJUlazlFMzewsgInwMICw4XFIDaRhOjCazHGv0OFdAhFQu6InTJ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-v6kmfkhk.us.auth0.com/